EDITOR_ASYNC="subl"
EDITOR="$EDITOR_ASYNC -w"

WS="$HOME/workspace"
GO_WS="$WS/projects/go"

GOPATH="$GO_WS"
PATH="$PATH:$WS/bin:$GO_WS/bin"

FG_DEFAULT="\[\e[0;0m\]"
FG_BLACK="\[\e[0;30m\]"
FG_RED="\[\e[0;31m\]"
FG_GREEN="\[\e[0;32m\]"
FG_YELLOW="\[\e[0;33m\]"
FG_BLUE="\[\e[0;34m\]"
FG_MAGENTA="\[\e[0;35m\]"
FG_CYAN="\[\e[0;36m\]"
FG_WHITE="\[\e[0;37m\]"

PS1="$FG_CYAN\W$FG_BLUE\$(branch \" \")$FG_DEFAULT "
PS2="$FG_CYAN>$FG_DEFAULT "

export PATH GOPATH EDITOR

alias a="ls -Galh"
alias b="cd $WS/bin"
alias c="cd $WS/clearing"
alias d="cd $WS/documents"
alias e="$EDITOR $HOME/.profile && . $HOME/.profile"
alias f="find 2>/dev/null -x / -name"
alias g="$EDITOR_ASYNC $GOPATH/src"
alias h="$EDITOR_ASYNC $(go env GOROOT)/src/pkg"
alias i="echo $(whoami) on $(hostname)"
#alias j=""
alias k="$EDITOR_ASYNC $WS/documents/bucket_lists"
alias l="ls -Ga"
#alias m=""
alias n="$EDITOR_ASYNC $WS/documents/notes"
#alias o=""
alias p="cd $WS/projects"
#alias q=""
alias r="echo \$?"
alias s="mdfind -name"
#alias t=""
alias u="cd .."
#alias v=""
alias w="cd $WS"
#alias x=""
#alias y=""
alias z="cd -"
